"use client";
import { createContext, useState } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

import MyNavbar from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const pagecontext = createContext();
export default function RootLayout({ children }) {
  const [pages, setpages] = useState();
  const [searchTerm, setsearchTerm] = useState("");
  return (
    <html lang="en">
      <pagecontext.Provider
        value={{ pages, setpages, searchTerm, setsearchTerm }}
      >
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <MyNavbar />
          {children}
        </body>
      </pagecontext.Provider>
    </html>
  );
}
export { pagecontext };
